### ISSUE TITLE
invalid IP

### ISSUE THREAD

**Issue by Derek-Lehrke** [udotdevelopment/ATSPM#20]
IP 0.0.0.0 will cause "FTPfromAllControllers" to crash

`Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: address
   at System.Net.NetworkInformation.Ping.Send(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   at System.Net.NetworkInformation.Ping.Send(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options)
   at FTPfromAllControllers.FTPfromAllControllers.CheckIfIPAddressIsValid(Signal signal) in c:\Projects\Branches\SignalPerformanceMetrics\v4.0.1\FTPfromasc3\Program.cs:line 195
   at FTPfromAllControllers.FTPfromAllControllers.<>c__DisplayClass3.<Main>b__2(<>f__AnonymousType1`9 row) in c:\Projects\Branches\SignalPerformanceMetrics\v4.0.1\FTPfromasc3\Program.cs:line 105
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 local
Finally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at FTPfromAllControllers.FTPfromAllControllers.Main(String[] args) in c:\Projects\Branches\SignalPerformanceMetrics\v4.0.1\FTPfromasc3\Program.cs:line 166`

**Comment by shanejohnson-udot** [comment]
I fixed this in the check IP address method and added unit tests to show the method work the way I think it should.
